# Generated by Django 4.1.7 on 2023-02-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='article_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
