# Generated by Django 4.1.7 on 2023-02-19 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_newsarticle_article_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='title',
        ),
    ]
