# Generated by Django 4.1.7 on 2023-02-19 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_newsarticle_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsarticle',
            old_name='url',
            new_name='link',
        ),
    ]
