# Generated by Django 4.1.7 on 2023-02-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_userlikednews'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='published_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
