# Generated by Django 4.1.7 on 2023-02-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_userlikednews'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlikednews',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
