# Generated by Django 4.1.7 on 2023-02-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_userlikednews_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlikednews',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
