# Generated by Django 4.1.7 on 2023-02-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_userlikednews_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='fetched_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
